# Generated by Django 4.2.4 on 2023-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('AC', 'Ac'), ('Carpentry', 'Carpentry'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Water management', 'Water Management'), ('Girls Hostel', 'Girls Hostel'), ('Boys Hostel', 'Boys Hostel')], default='AC', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='To Do', max_length=25),
        ),
    ]
